# Theming / Appearance
theme = "tokyonight"

# editor
[editor]
line-number = "relative"
shell = ["zsh", "-c"]

[editor.auto-save]
focus-lost = true

###
#### Config
### 
[keys.insert.j]
k = "normal_mode" # Maps `jk` to exit insert mode

